---
title: "Lab 05 - Wrangling Spatial Data "
author: "Lilly McClendon"
date: "02-21-2025"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox) 
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
```

### Exercise 1

```{r view-dennys-laquinta-data}
view(dennys)
view(laquinta)
```

```{r filter-dennys-alaska}
dn_ak <- dennys %>%
  filter(state == "AK")
nrow(dn_ak)
view(dn_ak)
```

```{r filter-laquinta-alaska}
lq_ak <- laquinta %>%
  filter(state == "AK")
nrow(lq_ak)
view(lq_ak)
```

### Exercise 2

#### Total combinations of Denny's and La Quinta Locations 

```{r filter-dennys-laquinta-alaska-combinations}
total_combinations <- nrow(dn_ak) * nrow(lq_ak)
print(total_combinations)
```

There are 6 total combinations of Denny's and La Quinta locations in Alaska. 


### Exercise 3

#### Joining Denny's in Alaska and La Quinta in Alaska datasets 

```{r join-dennys-ak-laquinta-ak}
dn_lq_ak <- full_join(dn_ak, lq_ak, 
                      by = "state")
dn_lq_ak
```

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...

Add exercise headings as needed.
